print("Hello, world!")
print('Grace Hopper was an American computer scientist.')
print('She was one of the first programmers of the Harvard Mark I computer.')
print('She invented on of the first linkers')
input("Have you heard of Grace Hopper before?")
print("They are pretty cool aren't they.")

print("    ----------     ")
print("    |        |     ")
print("    |        |     ")
print("    |        |     ")
print("    |        |     ")
print("    ----------     ")
